version: "1.0"
info:
  model: int-scaffold
packages:
- name: SE_TS_IntegrationDemoProject
  gitServerName: SE_TS_Github
  gitUrl: https://github.com/tsvens
  gitUsername: tsvens
  gitBranch: main
- name: MMXDemoPackage
  version: "1.0"
  gitServerName: SE_TS_Github
  gitUrl: https://github.com/tsvens
  gitUsername: tsvens
  gitBranch: master
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
services:
- serviceName: project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:SE_TS_EdgeDB
  packages:
  - name: SE_TS_IntegrationDemoProject
    version: "1.0"
  - name: MMXDemoPackage
    version: "1.0"
configurationVariables:
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.driverType
  : MySQLJDBC
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.trustStore
  : ""
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.keyStore
  : ""
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.serverName
  : mysql-cred.mysql
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.otherProperties
  : loginTimeout=60;
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.datasourceClass
  : com.mysql.cj.jdbc.MysqlDataSource
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.dbType
  : MySQL
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.user
  : crunchops
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.networkProtocol
  : ""
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.databaseName
  : demodb
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.portNumber
  : "3306"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionSettings.password
  : "{AES}AsegY28Coi/S17V4BYq2Cw=="
  ? artConnection.SE_TS_IntegrationDemoProject.project.se_ts_integrationdemo.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.SE_TS_EdgeDB.connectionEnabled
  : "false"
